### PR TITLE
Success indicator

### PR DESCRIPTION
**Pull request by agouin**
If the webview is already authenticated into an active session, it will flicker quickly and exit, which does not provide a great UX. This adds a default indicator to inform the user that the authentication was successful and that they can safely close the window, or it will automatically close after 5 seconds. A flag is also added so that this can be disabled with `--quiet`

Image is nothing special, was quickly generated with midjourney.

image

### CODE REVIEW

**Comment by gm-vm** [comment]
I don't know how I feel about this one. I'd rather delay the creation of the screen, so that if the cookie is already there the window won't even appear. I can't really test this, but could something like this help?

```diff
diff --git a/openfortivpn-webview-qt/main.cpp b/openfortivpn-webview-qt/main.cpp
index 90e3747..bfa85f3 100644
--- a/openfortivpn-webview-qt/main.cpp
+++ b/openfortivpn-webview-qt/main.cpp
@@ -95,7 +95,6 @@ int main(int argc, char *argv[])
     w.loadUrl(url);
     w.resize(1024, 760);
     w.move(findScreenWithCursor()->geometry().center() - w.rect().center());
-    w.show();
 
     return app.exec();
 }
diff --git a/openfortivpn-webview-qt/mainwindow.cpp b/openfortivpn-webview-qt/mainwindow.cpp
index 289cde3..edcb5e5 100644
--- a/openfortivpn-webview-qt/mainwindow.cpp
+++ b/openfortivpn-webview-qt/mainwindow.cpp
@@ -50,6 +50,8 @@ MainWindow::MainWindow(const bool keepOpen,
             &MainWindow::onCookieRemoved);
 
     connect(webEnginePage, &QWebEnginePage::certificateError, this, &MainWindow::onCertificateError);
+
+    connect(webEnginePage, &QWebEnginePage::loadFinished, this, [this] { show(); }, Qt::SingleShotConnection);
 }
 
 MainWindow::~MainWindow()
```

I'm not sure when the "loaded" event fires, especially when dealing with pages with tons of javascript, but even adding a barely noticeable fixed delay could help.

**Comment by agouin** [comment]
It works! I prefer the no indicator route much better.

**Comment by gm-vm** [comment]
Done, I pushed the change straight to main.

**Comment by agouin** [comment]
Thank you! 

Closing in favor of https://github.com/gm-vm/openfortivpn-webview/commit/67ea38d3a46d6a97be58b1f493c6d5131eda18e5

**Pull request closed without merging**
