### PR TITLE
Add command line parameter for http proxy

### PR DESCRIPTION
**Pull request by oven**
Add option to use an HTTP proxy server when authenticating with AD

### CODE REVIEW

**Comment by gm-vm** [comment]
Do the standard `http_proxy` and `https_proxy` env variables work for you?

Something like this (you can even specify just one of the variables):
```
https_proxy=myhttpsproxy:1234 http_proxy=myhttpproxy:1234 openfortivpn-webview myvpnhost
```

**Comment by gm-vm** [comment]
By the way, it seems that the electron app just passes everything to Chromium, so this is actually working as well:

```
openfortivpn-webview --proxy-server=http://myproxy:1234 myvpnhost
```

If you use `npm start` you have to use pass it in this way instead:
```
npm start myvpnhost -- --proxy-server=http://asd.com:1234
```

This is also what I do to pass `--enable-logging --log-level=3`, as shown in the README of the project.

**Comment by oven** [comment]
I tried setting the http_proxy and https_proxy environment variables, but they don't seem to get picked up by Chromium. I tried both `HTTP_PROXY`, `HTTPS_PROXY`, `http_proxy` and `https_proxy`, and setting them to `<host>:<port>` and `http://<host>:<port>`. So that approach doesn't work, at least not on OS X where I tried it. 

Passing `--proxy-server` as an argument works, so that means this is more of a documentation issue. I'll make some changes and push a new commit :)

**Comment by oven** [comment]
I also added documentation on how to use http proxy on the QT variant, but I've not been able to test that.

**Comment by gm-vm** [comment]
Thanks for this.

I should probably simplify how the Qt app works and let callers to pass whatever they want, as it is done for Electron. Using that env variable is not that user friendly.

**Pull request merged**
